<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PerusahaanSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Maju Bersama Teknologi',
                'bidang_usaha'    => 'Teknologi Informasi',
                'alamat'          => 'Jl. Sudirman No. 12, Kel. Pinangsia',
                'kota'            => 'Jakarta',
                'no_telepon'      => '02112345678',
                'email'           => 'info@majubersama.co.id',
                'website'         => 'https://www.majubersama.co.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'CV Karya Mandiri Nusantara',
                'bidang_usaha'    => 'Konstruksi & Bangunan',
                'alamat'          => 'Jl. Ahmad Yani No. 45, Kel. Merdeka',
                'kota'            => 'Bandung',
                'no_telepon'      => '02287654321',
                'email'           => 'cs@karyamandiri.id',
                'website'         => 'https://www.karyamandiri.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Sejahtera Abadi Grup',
                'bidang_usaha'    => 'Perdagangan & Distribusi',
                'alamat'          => 'Jl. Diponegoro No. 8, Kel. Tegalsari',
                'kota'            => 'Surabaya',
                'no_telepon'      => '03198765432',
                'email'           => 'contact@sejahteraabadi.com',
                'website'         => 'https://www.sejahteraabadi.com',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Global Solusi Digital',
                'bidang_usaha'    => 'Teknologi Informasi',
                'alamat'          => 'Jl. Gatot Subroto Kav. 22',
                'kota'            => 'Semarang',
                'no_telepon'      => '02411122334',
                'email'           => 'hello@globalsolusi.tech',
                'website'         => 'https://www.globalsolusi.tech',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'CV Mitra Usaha Bersama',
                'bidang_usaha'    => 'Kuliner & F&B',
                'alamat'          => 'Jl. Malioboro No. 77',
                'kota'            => 'Yogyakarta',
                'no_telepon'      => '02744556677',
                'email'           => 'mub@mitrausaha.id',
                'website'         => 'https://www.mitrausaha.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Nusantara Energi Prima',
                'bidang_usaha'    => 'Energi & Pertambangan',
                'alamat'          => 'Jl. S. Parman No. 100, Kel. Palmerah',
                'kota'            => 'Jakarta',
                'no_telepon'      => '02133445566',
                'email'           => 'info@nusantaraenergi.co.id',
                'website'         => 'https://www.nusantaraenergi.co.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Cipta Kreasi Media',
                'bidang_usaha'    => 'Media & Periklanan',
                'alamat'          => 'Jl. Raya Darmo No. 56',
                'kota'            => 'Surabaya',
                'no_telepon'      => '03177889900',
                'email'           => 'halo@ciptakreasi.com',
                'website'         => 'https://www.ciptakreasi.com',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'CV Harapan Jaya Logistik',
                'bidang_usaha'    => 'Logistik & Ekspedisi',
                'alamat'          => 'Jl. Imam Bonjol No. 33',
                'kota'            => 'Medan',
                'no_telepon'      => '06188990011',
                'email'           => 'ops@harapanjaya.id',
                'website'         => 'https://www.harapanjaya.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Artha Kencana Finance',
                'bidang_usaha'    => 'Keuangan & Perbankan',
                'alamat'          => 'Jl. Asia Afrika No. 15',
                'kota'            => 'Bandung',
                'no_telepon'      => '02255667788',
                'email'           => 'info@arthakencana.co.id',
                'website'         => 'https://www.arthakencana.co.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id_user'         => null,
                'nama_perusahaan' => 'PT Bumi Hijau Agrikultur',
                'bidang_usaha'    => 'Pertanian & Agribisnis',
                'alamat'          => 'Jl. Pahlawan No. 9, Kel. Klojen',
                'kota'            => 'Malang',
                'no_telepon'      => '03411223344',
                'email'           => 'admin@bumihijau.co.id',
                'website'         => 'https://www.bumihijau.co.id',
                'logo'            => null,
                'is_active'       => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
        ];

        $this->db->table('tb_perusahaan')->insertBatch($data);
    }
}
